### ISSUE TITLE
QColdSweat qpkg?

### ISSUE THREAD

**Issue by ahaghgoo** [SkyCrawl/coldsweat-qpkg#1]
Hi I'm wondering where the qpkg is located for ColdSweat?  Tried using the link on the main page, but it gives me an error page.  Thanks for the consideration.  Really looking forward to trying this out.

**Comment by SkyCrawl** [comment]
Hey!

Sorry about that... I made some small changes recently and left the repository in a somewhat unfinished manner. I didn't think there would be anyone actually trying this out before there's a notice hanging in QNAP forums (which I planned to make soon) so you caught me off guard and surprised me, in a good way of course :).

I've made final improvements and released version 0.9.7-1 so you're all set now.

**Comment by SkyCrawl** [comment]
I will close this issue for now. If you have any trouble, please open a new one :).
