### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by TeeSee64** [SkyCrawl/coldsweat-qpkg#2]
Tried to install it on my QNAP TS-230, but it fails. For what i can see the problem is python

Collected errors:
 * opkg_install_cmd: Cannot install package python.
 * opkg_install_cmd: Cannot install package python-pip.
Unknown package 'python'.
Unknown package 'python-pip'.
Collected errors:
 * opkg_install_cmd: Cannot install package python-dev.
Unknown package 'python-dev'.

Python3 (3.3.6.1) is installed on the NAS.

[install.log](https://github.com/SkyCrawl/qcoldsweat/files/6216104/install.log)

**Comment by SkyCrawl** [comment]
Looks like Entware recently removed python2 from available packages and replaced it with python3. I could update the QPKG to reflect this, but [Coldsweat itself is not compatible with it](https://github.com/passiomatic/coldsweat/issues/109) and it's been discontinued last year. Sadly, I should also discontinue this project (I forgot to and thank you for reminding me).

As for an alternative, I recommend [FreshRSS](https://github.com/FreshRSS/FreshRSS) installed via QNAP Club. I'm using it now and so far, am happy with it.
